### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by nico202** [Nheko-Reborn/blurhash#1]
Hi, I wanted to package this for [guix](https://guix.gnu.org/).  We usually prefer to use tagged versions.  If this code is stable enough (and since is used in nheko I hope it does), would you mind tagging a version?

Thanks!

**Comment by deepbluev7** [comment]
Let's do that, when #2 is merged? Sorry about the inconveniences, I never thought about distros unbundling this from Nheko!

**Comment by nico202** [comment]
Yes, we should wait something  like #2 to be merged.

Np, it's just that some distro policy (for guix, but I think debian tries to do the same) is to unbundle everything when possible :)

**Comment by deepbluev7** [comment]
Yeah, I know that most distros prefer unbundling everything, which is why Nheko pulls all dependencies from the system by default. Only exception is this and the SingleApplication stuff, because I found no distribution to package them and they are mostly a single file. I just made this a separate project in hope, that it will be useful at some point to someone else, but it is really just 2 functions split out from Nheko. I guess making this a proper package makes sense though, so thanks for poking me!

**Comment by nico202** [comment]
In nheko CMakeLists.txt, I'm adding 
`pkg_check_modules(BLURHASH REQUIRED blurhash)`
and then `blurhash` after `liblmdb::lmdb`, and removing `third_party/blurhash/blurhash.cpp` from sources.

We can apply this patch to the build for 0.8.0, but if in the future it happens for you to fix also this it would be great.

(Same for guix about SingleApplication, we don't have it packaged yet even if probably we should)

**Comment by deepbluev7** [comment]
Yeah, we still need to provide an option to use the bundled version though, which makes this a bit more complex, but I'll see what I can do.

**Comment by deepbluev7** [comment]
Done!
